name: Release styles
on:
  release:
    types: [published]

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Get Repo
        uses: actions/checkout@v3

      - name: Generate glyphs
        run: npm install; npm run generate

      - name: Generate release file
        run: npm run release

      - name: Add file to release
        run: gh release upload $GITHUB_REF dist/styles.tar.gz --clobber
