name: Release styles
on:
  release:
    types: [published]

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: "Get release tag name"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: Get Repo
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: Generate glyphs
        run: npm run generate

      - name: Generate release files
        run: npm run release

      - name: Add file to release
        run: gh release upload $RELEASE_TAG dist/styles.tar.gz --clobber

      - name: Update release
        run: gh release edit $RELEASE_TAG --draft=false --latest --prerelease=false
